# Generated by Django 5.2.6 on 2025-09-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_number', models.IntegerField(primary_key=True, serialize=False)),
                ('chatgpt_a_question', models.TextField(default='What are your top 3 favorite foods?')),
                ('chatgpt_b_answer', models.JSONField()),
                ('is_vegetarian', models.BooleanField(default=False)),
            ],
        ),
    ]
